### ISSUE TITLE
No authentication applied

### ISSUE THREAD

**Issue by meghakundu** [Hafizcode02/laravel-blog#2]
Login/register form missing, only frontend pages are there i.e. homepage,category page and contact_us page. Please help with the content @hafizcode02

**Comment by hafizcode02** [comment]
Hi @meghakundu , this project is my learning project. the login/register form is not missing. simply you must access url /admin/login to access the login page or register first. this website project is using laravel breeze for authentication.

**Comment by meghakundu** [comment]
> Hi @meghakundu , this project is my learning project. the login/register form is not missing. simply you must access url /admin/login to access the login page or register first. this website project is using laravel breeze for authentication.

Thanks

**Comment by hafizcode02** [comment]
@meghakundu your welcome, glad to help you
